Slider movement #3
EmrNITK/Ping-Pong pull request #10
Opened 2023-08-31 06:12 UTC by yujit2003

2023-09-02 23:32 UTC, mr-prometheus requested changes
Since this would be the main working file, rename it to main.py.

Rest LGTM!!

2023-09-05 13:39 UTC, yujit2003 commented
ok... Sir :)))

2023-09-05 13:42 UTC, yujit2003 commented
Done !!🫡

2023-09-05 19:14 UTC, mr-prometheus approved these changes
LGTM!!

2023-09-05 19:14 UTC, merged